### ISSUE TITLE
Module incompatible with Elemental Userforms

### ISSUE THREAD

**Issue by robingram** [nswdpc/silverstripe-csp#2]
When used in conjunction with the [Elemental Userforms](https://github.com/dnadesign/silverstripe-elemental-userforms) module an error is raised if a form content block is on the page.

This is because `onAfterInit` in the controller extension expects the controller to be backed by an instance of `SiteTree`. That isn't necessarily the case in Silverstripe and in this instance the controller is `UserformsController` backed by an instance of the `ElementForm` data object. The error is raised because the type hinting on `getPagePolicy` enforces `SiteTree`.

As far as a fix goes I'm not sure if the type hinting should be relaxed or whether `checkCanRun` should check if the the controller is backed by a `SiteTree` instance - I don't know if the policy check is actually relevant to controllers backed by DOs as they aren't the actual page, at least not in this instance.

**Comment by JamesDPC** [comment]
Thanks for your report.
There was a PR in relation to this a month back or so: https://github.com/nswdpc/silverstripe-csp/pull/1

There have been a few updates since Sept but no releases that include those, can you try out master and see if that fixes the issue?

Thanks
James

**Comment by robingram** [comment]
Looks like that works @JamesDPC. Sorry I didn't spot the fix in `master` before raising the issue.
